name: Deploy Streamlit + Bedrock App to EC2 via ECR

on:
  push:
    branches: [main]

env:
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy Docker Image to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        id: build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPO }}
        run: |
          # Construct the full image URI
          IMAGE_URI=${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          echo "Built image: $IMAGE_URI"
          # Build and push the Docker image
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          # Save IMAGE_URI to the environment for subsequent steps
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Deploy to EC2 via SSH
        # Pass the IMAGE_URI from the environment into this step
        env:
          IMAGE_URI: ${{ env.IMAGE_URI }}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deploying image: $IMAGE_URI"
            docker stop streamlit-app || true
            docker rm streamlit-app || true
            docker pull $IMAGE_URI
            docker run -d \
              -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
              -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
              -e AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}" \
              -p 8501:8501 \
              --name streamlit-app \
              $IMAGE_URI
